package gg.troll.report.api.match.enums;

import lombok.Getter;

@Getter
public enum Champion {
    ANNIE(1, "Annie", "애니"),
    OLAF(2, "Olaf", "올라프"),
    GALIO(3, "Galio", "갈리오"),
    TWISTED_FATE(4, "Twisted Fate", "트위스티드 페이트"),
    XIN_ZHAO(5, "Xin Zhao", "신 짜오"),
    URGOT(6, "Urgot", "우르곳"),
    LEBLANC(7, "LeBlanc", "르블랑"),
    VLADIMIR(8, "Vladimir", "블라디미르"),
    FIDDLESTICKS(9, "Fiddlesticks", "피들스틱"),
    KAYLE(10, "Kayle", "케일"),
    MASTER_YI(11, "Master Yi", "마스터 이"),
    ALISTAR(12, "Alistar", "알리스타"),
    RYZE(13, "Ryze", "라이즈"),
    SION(14, "Sion", "사이온"),
    SIVIR(15, "Sivir", "시비르"),
    SORAKA(16, "Soraka", "소라카"),
    TEEMO(17, "Teemo", "티모"),
    TRISTANA(18, "Tristana", "트리스타나"),
    WARWICK(19, "Warwick", "워윅"),
    NUNU_AND_WILLUMP(20, "Nunu & Willump", "누누와 윌럼프"),
    MISS_FORTUNE(21, "Miss Fortune", "미스 포츈"),
    ASHE(22, "Ashe", "애쉬"),
    TRYNDAMERE(23, "Tryndamere", "트린다미어"),
    JAX(24, "Jax", "잭스"),
    MORGANA(25, "Morgana", "모르가나"),
    ZILEAN(26, "Zilean", "질리언"),
    SINGED(27, "Singed", "신지드"),
    EVELYNN(28, "Evelynn", "이블린"),
    TWITCH(29, "Twitch", "트위치"),
    KARTHUS(30, "Karthus", "카서스"),
    CHO_GATH(31, "Cho'Gath", "초가스"),
    AMUMU(32, "Amumu", "아무무"),
    RAMMUS(33, "Rammus", "람머스"),
    ANIVIA(34, "Anivia", "애니비아"),
    SHACO(35, "Shaco", "샤코"),
    DR_MUNDO(36, "Dr. Mundo", "문도 박사"),
    SONA(37, "Sona", "소나"),
    KASSADIN(38, "Kassadin", "카사딘"),
    IRELIA(39, "Irelia", "이렐리아"),
    JANNA(40, "Janna", "잔나"),
    GANGPLANK(41, "Gangplank", "갱플랭크"),
    CORKI(42, "Corki", "코르키"),
    KARMA(43, "Karma", "카르마"),
    TARIC(44, "Taric", "타릭"),
    VEIGAR(45, "Veigar", "베이가"),
    TRUNDLE(48, "Trundle", "트런들"),
    SWAIN(50, "Swain", "스웨인"),
    CAITLYN(51, "Caitlyn", "케이틀린"),
    BLITZCRANK(53, "Blitzcrank", "블리츠크랭크"),
    MALPHITE(54, "Malphite", "말파이트"),
    KATARINA(55, "Katarina", "카타리나"),
    NOCTURNE(56, "Nocturne", "녹턴"),
    MAOKAI(57, "Maokai", "마오카이"),
    RENEKTON(58, "Renekton", "레넥톤"),
    JARVAN_IV(59, "Jarvan IV", "자르반 4세"),
    ELISE(60, "Elise", "엘리스"),
    ORIANNA(61, "Orianna", "오리아나"),
    WUKONG(62, "Wukong", "오공"),
    BRAND(63, "Brand", "브랜드"),
    LEE_SIN(64, "Lee Sin", "리 신"),
    VAYNE(67, "Vayne", "베인"),
    RUMBLE(68, "Rumble", "럼블"),
    CASSIOPEIA(69, "Cassiopeia", "카시오페아"),
    SKARNER(72, "Skarner", "스카너"),
    HEIMERDINGER(74, "Heimerdinger", "하이머딩거"),
    NASUS(75, "Nasus", "나서스"),
    NIDALEE(76, "Nidalee", "니달리"),
    UDYR(77, "Udyr", "우디르"),
    POPPY(78, "Poppy", "뽀삐"),
    GRAGAS(79, "Gragas", "그라가스"),
    PANTHEON(80, "Pantheon", "판테온"),
    EZREAL(81, "Ezreal", "이즈리얼"),
    MORDEKAISER(82, "Mordekaiser", "모데카이저"),
    YORICK(83, "Yorick", "요릭"),
    AKALI(84, "Akali", "아칼리"),
    KENNEN(85, "Kennen", "케넨"),
    GAREN(86, "Garen", "가렌"),
    LEONA(89, "Leona", "레오나"),
    MALZAHAR(90, "Malzahar", "말자하"),
    TALON(91, "Talon", "탈론"),
    RIVEN(92, "Riven", "리븐"),
    KOG_MAW(96, "Kog'Maw", "코그모"),
    SHEN(98, "Shen", "쉔"),
    LUX(99, "Lux", "럭스"),
    XERATH(101, "Xerath", "제라스"),
    SHYVANA(102, "Shyvana", "쉬바나"),
    AHRI(103, "Ahri", "아리"),
    GRAVES(104, "Graves", "그레이브즈"),
    FIZZ(105, "Fizz", "피즈"),
    VOLIBEAR(106, "Volibear", "볼리베어"),
    RENGAR(107, "Rengar", "렝가"),
    VARUS(110, "Varus", "바루스"),
    NAUTILUS(111, "Nautilus", "노틸러스"),
    VIKTOR(112, "Viktor", "빅토르"),
    SEJUANI(113, "Sejuani", "세주아니"),
    FIORA(114, "Fiora", "피오라"),
    ZIGGS(115, "Ziggs", "직스"),
    LULU(117, "Lulu", "룰루"),
    DRAVEN(119, "Draven", "드레이븐"),
    HECARIM(120, "Hecarim", "헤카림"),
    KHA_ZIX(121, "Kha'Zix", "카직스"),
    DARIUS(122, "Darius", "다리우스"),
    JAYCE(126, "Jayce", "제이스"),
    LISSANDRA(127, "Lissandra", "리산드라"),
    DIANA(131, "Diana", "다이애나"),
    QUINN(133, "Quinn", "퀸"),
    SYNDRA(134, "Syndra", "신드라"),
    AURELION_SOL(136, "Aurelion Sol", "아우렐리온 솔"),
    KAYN(141, "Kayn", "케인"),
    ZOE(142, "Zoe", "조이"),
    ZYRA(143, "Zyra", "자이라"),
    KAI_SA(145, "Kai'Sa", "카이사"),
    SERAPHINE(147, "Seraphine", "세라핀"),
    GNAR(150, "Gnar", "나르"),
    ZAC(154, "Zac", "자크"),
    YASUO(157, "Yasuo", "야스오"),
    VEL_KOZ(161, "Vel'Koz", "벨코즈"),
    TALIYAH(163, "Taliyah", "탈리야"),
    CAMILLE(164, "Camille", "카밀"),
    BRAUM(201, "Braum", "브라움"),
    JHIN(202, "Jhin", "진"),
    KINDRED(203, "Kindred", "킨드레드"),
    JINX(222, "Jinx", "징크스"),
    TAHM_KENCH(223, "Tahm Kench", "탐 켄치"),
    SENNA(235, "Senna", "세나"),
    LUCIAN(236, "Lucian", "루시안"),
    ZED(238, "Zed", "제드"),
    KLED(240, "Kled", "클레드"),
    EKKO(245, "Ekko", "에코"),
    QIYANA(246, "Qiyana", "키아나"),
    VI(254, "Vi", "바이"),
    AATROX(266, "Aatrox", "아트록스"),
    NAMI(267, "Nami", "나미"),
    AZIR(268, "Azir", "아지르"),
    YUUMI(350, "Yuumi", "유미"),
    SAMIRA(360, "Samira", "사미라"),
    THRESH(412, "Thresh", "쓰레쉬"),
    ILLAOI(420, "Illaoi", "일라오이"),
    REK_SAI(421, "Rek'Sai", "렉사이"),
    IVERN(427, "Ivern", "아이번"),
    KALISTA(429, "Kalista", "칼리스타"),
    BARD(432, "Bard", "바드"),
    RAKAN(497, "Rakan", "라칸"),
    XAYAH(498, "Xayah", "자야"),
    ORNN(516, "Ornn", "오른"),
    SYLAS(517, "Sylas", "사일러스"),
    NEEKO(518, "Neeko", "니코"),
    APHELIOS(523, "Aphelios", "아펠리오스"),
    RELL(526, "Rell", "렐"),
    PYKE(555, "Pyke", "파이크"),
    YONE(777, "Yone", "요네"),
    SETT(875, "Sett", "세트"),
    LILLIA(876, "Lillia", "릴리아"),
    UNKNOWN(0, "Unknown", "Unknown");

    int championId;
    String championNameEn;
    String championNameKr;

    Champion(int championId, String championNameEn, String championNameKr) {
        this.championId = championId;
        this.championNameEn = championNameEn;
        this.championNameKr = championNameKr;
    }

    public static Champion of(int championId) {
        for (Champion champion : values()) {
            if (champion.getChampionId() == championId) {
                return champion;
            }
        }

        return UNKNOWN;
    }
}
